/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import clases.ConexionMySQL;
import clases.ConexionPostgreSQL;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sebastian
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
        Crear_Modelo();
        Consultar();    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnIngresar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtMotor = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbLista = new javax.swing.JTable();
        btnEliminar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_bookmark_filled_100px_2.png"))); // NOI18N

        btnIngresar.setBackground(new java.awt.Color(104, 150, 173));
        btnIngresar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnIngresar.setForeground(new java.awt.Color(255, 255, 255));
        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(104, 150, 173));
        btnSalir.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Conectado con:");

        txtMotor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMotor.setText("MOTOR");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnIngresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtMotor)
                                    .addComponent(jLabel3))))
                        .addGap(0, 43, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel1)
                .addGap(54, 54, 54)
                .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMotor)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 470));

        jPanel2.setBackground(new java.awt.Color(62, 81, 101));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Lista de libros ingresados");

        tbLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Descripción", "Autor", "Nota", "Fecha"
            }
        ));
        tbLista.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(tbLista);

        btnEliminar.setBackground(new java.awt.Color(62, 81, 101));
        btnEliminar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(204, 204, 204));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnActualizar.setBackground(new java.awt.Color(62, 81, 101));
        btnActualizar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(204, 204, 204));
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 620, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
      
      String nomM = txtMotor.getText();
      
      libros.Libros.motor2.setVisible(true);
      libros.Libros.motor2.txtMotor2.setText(nomM);
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
       dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
    Crear_Modelo();
    Consultar();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int filasel = tbLista.getSelectedRow();
        int resp;
        String MotorD = txtMotor.getText();
        
        if (MotorD == "MySQL"){
        ConexionMySQL Con = new ConexionMySQL();
        Con.ConectarBD();
        
         String id =  tbLista.getValueAt(filasel, 0).toString();

        if(filasel==-1){
             JOptionPane.showMessageDialog(null, "Debe seleccionar el libro a eleminar");
         }else{
             resp = JOptionPane.showConfirmDialog(null, "¿Estas seguro de eliminar este libro?","Eliminar",JOptionPane.YES_NO_OPTION);
             if(resp==JOptionPane.YES_OPTION){
                
                try{
                                      
                     String QUERY = "DELETE FROM libros "
                                + "WHERE codigo='"+id+"'"; 
                                   Con.sentencia.execute(QUERY);
                                   Crear_Modelo();
                                   Consultar();
                                   JOptionPane.showMessageDialog(null,"¡Los datos fueron eliminados con exito!");
                     
                 }catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, ex.getMessage() +"Error");
                  }
                 
             }
        }
        }else {
            
        ConexionPostgreSQL Conn = new ConexionPostgreSQL();
        Conn.ConectarBD();
        
         String id =  tbLista.getValueAt(filasel, 0).toString();

        if(filasel==-1){
             JOptionPane.showMessageDialog(null, "Debe seleccionar el libro a eleminar");
         }else{
             resp = JOptionPane.showConfirmDialog(null, "¿Estas seguro de eliminar este libro?","Eliminar",JOptionPane.YES_NO_OPTION);
             if(resp==JOptionPane.YES_OPTION){
                
                try{
                                      
                     String QUERY = "DELETE FROM libros "
                                + "WHERE codigo='"+id+"'"; 
                                   Conn.sentencia.execute(QUERY);
                                   Crear_Modelo();
                                   Consultar();
                                   JOptionPane.showMessageDialog(null,"¡Los datos fueron eliminados con exito!");
                     
                 }catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, ex.getMessage() +"Error");
                  }
                 
             }
        }
            
        }
        
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }
    

          
    

    DefaultTableModel modelo;
    public void Crear_Modelo (){
       
        try { 
            modelo = (new DefaultTableModel (
                    null, new String []{
                      "ID","Nombre", "Descripción",
                        "Autor ","Nota","Fecha "}) {
                            Class[] types = new Class[] {
                                java.lang.String.class,java.lang.String.class,
                                java.lang.String.class,java.lang.String.class,
                                java.lang.String.class,java.lang.String.class,
                               
                            };
                            boolean[] canEdit = new boolean[] {
                                 false,false,false,false,false,false
                            };
                            public Class getColumnClass(int columnIndex) {
                                return types[columnIndex];
                            }
                            public boolean isCellEditable(int rowIndex, int colIndex) {
                                return canEdit[colIndex];
                            }
                    });
            tbLista.setModel(modelo);
          // tbLista.getColumnModel().getColumn(0).setPreferredWidth(0);
            /*tbLista.getColumnModel().getColumn(2).setMaxWidth(160);
            tbLista.getColumnModel().getColumn(3).setPreferredWidth(110);
            tbLista.getColumnModel().getColumn(3).setMaxWidth(110);*/
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.toString() + "Error");
        }
        }
    
      public void Consultar() {
          
         String MySQL = "MySQL";
         String PostgreSQL  = "PostgreSQL";
         String MotorD = txtMotor.getText(); 
          
        try{
           int i = 0; Object Ob[]=null;
            
           if(MotorD == MySQL){
               
            ConexionMySQL Con = new ConexionMySQL();
            Con.ConectarBD();
            
            String SQL = "SELECT * FROM libros";
            Con.resultado = Con.sentencia.executeQuery(SQL);
            while (Con.resultado.next()) {
                modelo.addRow(Ob);
                modelo.setValueAt(Con.resultado.getString("codigo"),i,0);
                modelo.setValueAt(Con.resultado.getString("nombre"),i,1);
                modelo.setValueAt(Con.resultado.getString("descripcion"), i,2);
                modelo.setValueAt(Con.resultado.getString("nombre_autor"), i,3);
                modelo.setValueAt(Con.resultado.getString("nota"), i,4);
                modelo.setValueAt(Con.resultado.getString("fecha"), i,5);
                i++;
            }
            Con.DesconectarBD();
            
           }else{
               
               ConexionPostgreSQL Conn = new ConexionPostgreSQL();
               Conn.ConectarBD();
               
               String SQL = "SELECT * FROM libros";
               Conn.resultado = Conn.sentencia.executeQuery(SQL);
               while (Conn.resultado.next()) {
                modelo.addRow(Ob);
                modelo.setValueAt(Conn.resultado.getString("codigo"),i,0);
                modelo.setValueAt(Conn.resultado.getString("nombre"),i,1);
                modelo.setValueAt(Conn.resultado.getString("descripcion"), i,2);
                modelo.setValueAt(Conn.resultado.getString("nombre_autor"), i,3);
                modelo.setValueAt(Conn.resultado.getString("nota"), i,4);
                modelo.setValueAt(Conn.resultado.getString("fecha"), i,5);
                i++;
            }
            Conn.DesconectarBD();
               
           }
           

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null , ex.getMessage()+ " Error");     
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbLista;
    public javax.swing.JLabel txtMotor;
    // End of variables declaration//GEN-END:variables
}
